# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        # auto fix
        args: [--fix]
        exclude: ^docs
      - id: ruff-format
        exclude: ^docs